# Generated by Django 4.0.6 on 2022-08-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('user_college', models.CharField(choices=[('Revelle', 'Revelle'), ('Muir', 'Muir'), ('Marshall', 'Marshall'), ('Warren', 'Warren'), ('ERC', 'ERC'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh')], max_length=200, null=True)),
                ('user_major', models.CharField(choices=[('Math', 'Mathematics'), ('CS', 'Computer Science'), ('Bio', 'Biology'), ('Japn', 'Japanese Studies'), ('Chem', 'Chemistry'), ('SE', 'Structural Engineering'), ('Phys', 'Physics'), ('EE', 'Electrical Engineering'), ('Poli', 'Political Science')], max_length=200)),

                # 地図: Change back to default='profile1.png'
                ('profile_pic', models.
                ImageField(blank=True, default="../icons/pfp.png", null=True, upload_to='')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user_interest1', models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set'), ('Travel', 'Traveling'), ('CS', 'Counter Strike'), ('LoL', 'League of Legends'), ('Football', 'Football')], max_length=40)),
                ('user_interest2', models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set'), ('Travel', 'Traveling'), ('CS', 'Counter Strike'), ('LoL', 'League of Legends'), ('Football', 'Football')], max_length=40)),
                ('user_interest3', models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set'), ('Travel', 'Traveling'), ('CS', 'Counter Strike'), ('LoL', 'League of Legends'), ('Football', 'Football')], max_length=40)),
                ('current_courses', models.ManyToManyField(blank=True, related_name='current_courses_set', to='tutoring.course')),
                ('past_courses', models.ManyToManyField(blank=True, related_name='past_courses_set', to='tutoring.course')),
                ('student_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutoring_courses', models.ManyToManyField(blank=True, related_name='tutoring_courses_set', to='tutoring.course')),
            ],
        ),
    ]
