# Generated by Django 4.1 on 2022-08-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_user_karma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='last_name',
        ),
    ]
