# Generated by Django 4.0.6 on 2022-07-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingMatching',
        ),
    ]
