# Generated by Django 4.0.6 on 2022-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_student_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discord',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ig',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
