# Generated by Django 4.0.6 on 2022-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_courses',
            field=models.ManyToManyField(blank=True, related_name='current_courses_set', to='student.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='past_courses',
            field=models.ManyToManyField(blank=True, related_name='past_courses_set', to='student.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutoring_courses',
            field=models.ManyToManyField(blank=True, related_name='tutoring_courses_set', to='student.course'),
        ),
    ]
