# Generated by Django 4.0.6 on 2022-07-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Complete', 'Complete')], max_length=200, null=True),
        ),
    ]
