# Generated by Django 4.0.6 on 2022-07-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_dept', models.CharField(choices=[('CSE', 'CSE'), ('MATH', 'MATH'), ('COGS', 'COGS'), ('POLI', 'POLI')], max_length=10)),
                ('course_num', models.IntegerField()),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=25)),
                ('user_lname', models.CharField(max_length=25)),
                ('user_college', models.CharField(choices=[('Warren', 'Warren College'), ('Marshall', 'Marshall College'), ('Muir', 'John Muir College'), ('Revelle', 'Revelle College'), ('ERC', 'ERC'), ('Sixth', 'Sixth College'), ('Seventh', 'Seventh College')], max_length=10)),
                ('user_major', models.CharField(choices=[('Math', 'Mathematics'), ('CS', 'Computer Science'), ('Bio', 'Biology'), ('Japn', 'Japanese Studies'), ('Chem', 'Chemistry')], max_length=25)),
                ('user_interest1', models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set')], max_length=40)),
                ('user_interest2', models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set')], max_length=40)),
                ('user_interest3', models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set')], max_length=40)),
                ('user_courses', models.ManyToManyField(to='connection.course')),
            ],
        ),
    ]
