# Generated by Django 4.0.6 on 2022-07-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_alter_user_info_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_college',
            field=models.CharField(choices=[('Warren', 'Warren College'), ('Marshall', 'Marshall College'), ('Muir', 'John Muir College'), ('Revelle', 'Revelle College'), ('ERC', 'Eleanor Roosevelt College'), ('Sixth', 'Sixth College'), ('Seventh', 'Seventh College')], max_length=10),
        ),
    ]
