# Generated by Django 4.0.6 on 2022-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_alter_user_info_user_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_1', models.IntegerField()),
                ('id_user_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pending_matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sender', models.IntegerField()),
                ('id_receiver', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MATH', 'MATH'), ('COGS', 'COGS'), ('POLI', 'POLI'), ('CHEM', 'CHEM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_interest1',
            field=models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set'), ('Travel', 'Traveling'), ('CS', 'Counter Strike'), ('LoL', 'League of Legends'), ('Football', 'Football')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_interest2',
            field=models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set'), ('Travel', 'Traveling'), ('CS', 'Counter Strike'), ('LoL', 'League of Legends'), ('Football', 'Football')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_interest3',
            field=models.CharField(choices=[('Anime', 'Anime'), ('WoW', 'World of Warcraft'), ('Racoon', 'Racoon Watching'), ('Speeding', 'Driving over speed limit'), ('HW', 'Doing Problem Set'), ('Travel', 'Traveling'), ('CS', 'Counter Strike'), ('LoL', 'League of Legends'), ('Football', 'Football')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_major',
            field=models.CharField(choices=[('Math', 'Mathematics'), ('CS', 'Computer Science'), ('Bio', 'Biology'), ('Japn', 'Japanese Studies'), ('Chem', 'Chemistry'), ('SE', 'Structural Engineering'), ('Phys', 'Physics'), ('EE', 'Electrical Engineering'), ('Poli', 'Political Science')], max_length=25),
        ),
    ]
