# Generated by Django 4.0.6 on 2022-07-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_all_matching_pending_matching_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_matching',
            new_name='Finalized_matching',
        ),
    ]
