# Generated by Django 4.0.6 on 2022-07-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_rename_all_matching_finalized_matching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='ConnUser',
        ),
        migrations.RenameModel(
            old_name='Finalized_matching',
            new_name='FinalizedMatching',
        ),
        migrations.RenameModel(
            old_name='Pending_matching',
            new_name='PendingMatching',
        ),
    ]
