# Generated by Django 4.0.6 on 2022-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_rename_user_info_connuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connuser',
            name='user_fname',
        ),
        migrations.RemoveField(
            model_name='connuser',
            name='user_lname',
        ),
        migrations.AddField(
            model_name='pendingmatching',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
