# Generated by Django 4.0.6 on 2022-07-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_remove_connuser_user_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingmatching',
            old_name='isAccepted',
            new_name='isDenied',
        ),
    ]
