# Generated by Django 4.0.6 on 2022-08-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0008_rename_isaccepted_pendingmatching_isdenied'),
    ]

    operations = [
        migrations.AddField(
            model_name='connuser',
            name='user_karma',
            field=models.IntegerField(default=0),
        ),
    ]
